### ISSUE TITLE
content5 de tab5 en Empleados.php (y cualquier otra pagina) not showing

### ISSUE THREAD

**Issue by fdzalex** [kamgmc/AirUcab#1]
Primero, actualizamos `custom.css`:
```css
#tab0:checked ~ #content0,
#tab1:checked ~ #content1,
#tab2:checked ~ #content2,
#tab3:checked ~ #content3,
#tab4:checked ~ #content4,
/* added line */
#tab5:checked ~ #content5{
  display: block; 
}
```
En `empleados.php` creamos:
```html
<input id="tab5" type="radio" name="tabs" class="no-display">
<label for="tab5" class="label"><i class="fa fa-wifi" aria-hidden="true"></i> Tipo Contacto</label>
```
y en `empleados.php` agregamos:
```html
<section id="content5" class="sectiontab">
<!-- Cualquier cantidad de contenido aqui
.
.
.
 -->
</section>
```

y el TAB se muestra, pero el contenido no se visualiza, cambiando los `ID` de los tab genera que se vea, pero el ID cambiado luego no se ve.

---

El bug aplica a cualquier pagina donde se trate de hacer esta modificacion.

---
Sospecha: el problema debe estar en la relacion entre `custom.css` y la pagina o los _permisos_.
